global:
  # endpoints:
  #   - 1.2.3.4
  #   - 4.3.2.1
transformations:
  - name: web
    nodeSelector:
      - matchExpressions:
          - key: hostname
            operator: Regexp
            values:
              - ^web-.+$
    annotations:
      talos.dev/instance-id: "id-{{ .InstanceID }}"
    labels:
      node-role.kubernetes.io/web: ""
    taints:
      node.cloudprovider.kubernetes.io/storage-type: "NoSchedule"
