global:
  # endpoints:
  #   - 1.2.3.4
  #   - 4.3.2.1
transformations:
  - name: web
    nodeSelector:
      - matchExpressions:
          - key: hostname
            operator: Regexp
            values:
              - ^web-.+$
    annotations:
      talos.dev/instance-id: "id-{{ .InstanceID }}"
    labels:
      node-role.kubernetes.io/web: ""
    taints:
      node.cloudprovider.kubernetes.io/storage-type: "NoSchedule"

  - name: nocloud
    nodeSelector:
      - matchExpressions:
          - key: platform
            operator: In
            values:
              - nocloud
    platformMetadata:
      InstanceType: "{{ coalesce .InstanceType .SKUNumber }}"
      ProviderID: '{{ if .SerialNumber }}proxmox://region-1/{{ getValue .SerialNumber "i" }}{{ else }}{{ .ProviderID }}{{ end }}'
