style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/dhaines/talos-cloud-controller-manager
options:
  commits:
    filters:
      Type:
        - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: Features
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
