apiVersion: apps/v1
{{- if .Values.daemonSet.enabled }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "talos-cloud-controller-manager.fullname" . }}
  labels:
    {{- include "talos-cloud-controller-manager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.daemonSet.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  {{- else }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "talos-cloud-controller-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "talos-cloud-controller-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "talos-cloud-controller-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.daemonSet.enabled }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- end }}
      priorityClassName: {{ default  "system-cluster-critical" .Values.priorityClassName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/talos-cloud-controller-manager"]
          args:
            - --v={{ .Values.logVerbosityLevel }}
            - --cloud-provider=talos
            - --cloud-config=/etc/talos/ccm-config.yaml
            - --controllers={{- trimAll "," (include "talos-cloud-controller-manager.enabledControllers" . ) }}
            - --leader-elect-resource-name=cloud-controller-manager-talos
            - --use-service-account-credentials
            - --secure-port={{ .Values.service.containerPort }}
            - --authorization-always-allow-paths=/healthz,/livez,/readyz,/metrics
          {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          {{- if .Values.daemonSet.enabled }}
            - name: TALOS_ENDPOINTS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_SERVICE_HOST
              {{- if .Values.daemonSet.k8s.serviceHost }}
              value: {{ .Values.daemonSet.k8s.serviceHost }}
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- end }}
            - name: KUBERNETES_SERVICE_PORT
              value: {{ quote .Values.daemonSet.k8s.servicePort }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cloud-config
              mountPath: /etc/talos
              readOnly: true
            - name: talos-secrets
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.daemonSet.enabled }}
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
      {{- end }}
      volumes:
        - name: cloud-config
          configMap:
            name: {{ include "talos-cloud-controller-manager.fullname" . }}
            defaultMode: 416 # 0640
        - name: talos-secrets
          secret:
            secretName: {{ include "talos-cloud-controller-manager.serviceAccountName" . }}-talos-secrets
            defaultMode: 416 # 0640
